<?php

/**
 * @OA\Schema(
 *      schema="CategoryListResponse",
 *      @OA\Property(
 *          property="type",
 *          type="string",
 *          default="success"
 *      ),
 *       @OA\Property(
 *            property="data",
 *            type="array",
 *            @OA\Items(
 *              ref="#/components/schemas/CategorySmall"
 *            )
 *       )
 * )
 * @OA\Schema (
 *     schema="CategorySmall",
 *     @OA\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @OA\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="slug",
 *         type="string"
 *     )
 * )
 * @OA\Schema(
 *      schema="CategoryItemDetailResponse",
 *      @OA\Property(
 *          property="type",
 *          type="string",
 *          default="success"
 *      ),
 *       @OA\Property(
 *            property="data",
 *            type="array",
 *            @OA\Items(
 *              ref="#/components/schemas/CategoryDetail"
 *            )
 *       )
 * )
 * @OA\Schema (
 *     schema="CategoryDetail",
 *     @OA\Property(
 *         property="current_page",
 *         type="integer"
 *     ),
 *     @OA\Property(
 *         property="data",
 *         type="array",
 *         @OA\Items(
 *             ref="#/components/schemas/CategoryDetailItem"
 *         ),
 *     ),
 *     @OA\Property(
 *         property="first_page_url",
 *         type="string"
 *     ),
 *      @OA\Property(
 *         property="from",
 *         type="integer"
 *     ),
 *     @OA\Property(
 *         property="next_page_url",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="path",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="per_page",
 *         type="integer"
 *     ),
 *     @OA\Property(
 *         property="prev_page_url",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="to",
 *         type="integer"
 *     )
 * )
 * @OA\Schema (
 *     schema="CategoryDetailItem",
 *     @OA\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="slug",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="logo",
 *         type="string"
 *     ),
 *     @OA\Property(
 *          property="category",
 *          ref="#/components/schemas/CategorySmall"
 *      ),
 * )
 * @OA\Schema(
 *      schema="ItemDetailResponse",
 *      @OA\Property(
 *          property="type",
 *          type="string",
 *          default="success"
 *      ),
 *       @OA\Property(
 *            property="data",
 *            ref="#/components/schemas/ItemDetail"
 *       )
 * )
 * @OA\Schema (
 *     schema="ItemDetail",
 *     @OA\Property(
 *         property="title",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="slug",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="logo",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="description",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="hours_work",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="phone",
 *         type="string",
 *         nullable="true"
 *     ),
 *     @OA\Property(
 *         property="website",
 *         type="string",
 *         nullable="true"
 *     ),
 *     @OA\Property(
 *          property="category",
 *          ref="#/components/schemas/CategorySmall"
 *     ),
 *     @OA\Property(
 *         property="meta_title",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="meta_keywords",
 *         type="string"
 *     ),
 *     @OA\Property(
 *         property="meta_description",
 *         type="string"
 *     )
 * )
 */
